user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log notice;
pid /run/nginx.pid;
include /usr/share/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
    access_log  /var/log/nginx/access.log  main;
    sendfile on;
    tcp_nopush on;
    keepalive_timeout 65;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80;
        server_name _;
        root /usr/share/nginx/html;
        index index.html;

        location /api/catalogue/ {
            rewrite ^/api/catalogue/(.*)$ /$1 break;
            proxy_pass http://catalogue-dev.rdevopsb89.online:8002;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/user/ {
            rewrite ^/api/user/(.*)$ /$1 break;
            proxy_pass http://user-dev.rdevopsb89.online:8001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/cart/ {
            rewrite ^/api/(.*)$ /$1 break;
            proxy_pass http://cart-dev.rdevopsb89.online:8003;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/shipping/ {
            rewrite ^/api/(.*)$ /$1 break;
            proxy_pass http://shipping-dev.rdevopsb89.online:8004;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/payment/ {
            rewrite ^/api/(.*)$ /$1 break;
            proxy_pass http://payment-dev.rdevopsb89.online:8005;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/ratings {
            rewrite ^/api/(.*)$ /$1 break;
            proxy_pass http://ratings-dev.rdevopsb89.online:8006;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/orders/ {
            rewrite ^/api/(.*)$ /$1 break;
            proxy_pass http://orders-dev.rdevopsb89.online:8007;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            try_files $uri $uri/index.html $uri.html /index.html;
        }

        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
            expires 7d;
            add_header Cache-Control "public";
        }
    }
}